## application.yml
management:
  security:
    enabled: false

server:
  port: 8090

spring:
  application:
    name: cloud-movie

---
spring:
  profiles: default
  datasource:
    initialize: true
    platform: h2
    url: jdbc:h2:mem:moviedb;
    username: sa
    password:
  h2:
    console:
      enabled: true

logging:
  path: log/  # default 'spring.log'
  level.root: INFO
  level.com.skcc.dao.ContentMapper: ERROR
  level.com.skcc: OFF

name: default!

---
spring:
  profiles: k8s
  application:
    name: cloud-movie-k8s
  datasource:
    initialize: true
    platform: maria
    url: jdbc:mysql://${CLOUD_MOVIE_DB_SERVICE_HOST}:${CLOUD_MOVIE_DB_SERVICE_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

name: k8s
